site_name: Geo4LibCamp
theme:
  name: material
  custom_dir: overrides
  logo: images/logo-no-text.jpg
  favicon: images/favicon.png
  palette:
    - primary: green
    - accent: deep purple
        
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.tabs.link
    
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
      
plugins:
  - search
  - table-reader
  
extra:
      generator: false
  
nav:
  - Home : index.md
  - About: about.md  
  - Past Events:
      - 2025: '2025/index.md'
      - 2024: '2024/index.md'
      - 2023: '2023/agenda.md'
      - 2022: '2022.md' 
      - 2021: '2021.md' 
      - 2020: '2020.md' 
      - 2019: 'https://geo4libcamp2019.sched.com' 
      - 2018: 'https://geo4libcamp2018.sched.com' 
      - 2017: 'https://geo4libcamp2017.sched.com'
      - 2016: 'https://geo4libcamp2016.sched.com'
  - Glossary : glossary.md

