site_name: Geo4LibCamp
theme:
  name: material
  logo: images/logo-no-text.jpg
  favicon: images/favicon.png
  palette:
    - scheme: gbl-custom
        
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-mkdocs.min.css
  - stylesheets/neoteroi-timeline.css
  - stylesheets/neoteroi-cards.css
  - stylesheets/neoteroi-gantt.css
  - stylesheets/neoteroi-spantable.css
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - neoteroi.timeline
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  
      
plugins:
  - search
  - table-reader
  - open-in-new-tab
  
  
nav:
  - Home : index.md
  - About: about.md
  - Agenda 2023 : 2023/agenda.md
  - Glossary : glossary.md

