site_name: Geo4LibCamp
theme:
  name: material
  custom_dir: overrides
  logo: images/logo-no-text.jpg
  favicon: images/favicon.png
  palette:
    - primary: green
#     - scheme: gbl-custom
        
  features:
    - navigation.expand
#     - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    
extra_css:
  - stylesheets/extra.css

  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  
      
plugins:
#   - search
  - table-reader
  - open-in-new-tab
  
extra:
      generator: false
  
  
nav:
  - Home : index.md
  - Minneapolis 2024: 
      - 'About Minneapolis': '2024/index.md'
      - 'Agenda' : '2024/agenda-2024.md'
  - About: about.md
  - Glossary : glossary.md

